### ISSUE TITLE
PGO and BOLT optimizations

### ISSUE THREAD

**Issue by AntonIXO** [everx-labs/ever-node#157]
Hello, 
I suggest to enable PGO and BOLT optimizations. It may increase performance up to 50% according this [page](https://www.phoronix.com/news/LLVM-Lands-BOLT).
[LTO option avalible in cargo right now](https://doc.rust-lang.org/cargo/reference/profiles.html#lto)
To use these optimization we need to create local benchmarks.
[Cargo exetention for PGO and BOLT](https://github.com/Kobzol/cargo-pgo)

**Comment by bvscd** [comment]
These types of optimization seems to be not reasonable to support. They both require several steps to apply:
1. Make initial build with necessary instrumentation
2. Run the program to collect profiling data
3. Second build with respect to data from previous step
This process may take very long time and requires proper profiling skills. Also node binary operation depends on many aspects (is it validator or not for example), so it is hard to do proper profiling in general case.
By the way, according to experiments, the performance boost for average app obtained after these optimization was not so sufficient (<5%), but time spent for single optimization run was around several hours
